version: "3.7"
name: tracardi-app

x-license: &license
  LICENSE: "paste-you-license-here"

x-api-config: &api-config
  ELASTIC_HOST: http://elasticsearch:9200
  REDIS_HOST: redis://redis:6379
  PULSAR_HOST: pulsar://pulsar:6650
  MYSQL_HOST: mysql
  LOGGING_LEVEL: "info"
  DEMO: "no"
  MULTI_TENANT: "no"
  MULTI_TENANT_MANAGER_URL: "http://tracardi-tms"
  MULTI_TENANT_MANAGER_API_KEY: "604e5043-a28f-4b4d-baa7-13eb196e7537"
  ENABLE_VISIT_ENDED: "yes"
  ENABLE_WORKFLOW: "yes"
  ENABLE_PROFILE_DESTINATIONS: "yes"
  ENABLE_EVENT_DESTINATIONS: "yes"
  ENABLE_FIELD_UPDATE_LOG: "yes"
  AUTO_PROFILE_MERGING: "1234567890-qwertyuiopasdfghjkl"

services:

  tracardi-apm:
    image: tracardi/apm:1.1.10
    container_name: tracardi-apm
    restart: always
    environment:
      ELASTIC_HOST: http://elasticsearch:9200
      REDIS_HOST: redis://redis:6379
      PULSAR_HOST: pulsar://pulsar:6650
      MYSQL_HOST: mysql
      LOGGING_LEVEL: "info"
      AUTO_PROFILE_MERGING: "1234567890-qwertyuiopasdfghjkl"
      MODE: "worker"
      <<: *license

    networks:
      - tracardi-network

  tracardi-private-api:
    image: tracardi/com-tracardi-api:1.1.10
    container_name: tracardi-private-api
    restart: always
    environment:
      PRODUCTION: "no"
      EXPOSE_GUI_API: "yes"
      <<: *api-config
      <<: *license
    ports:
      - 8686:80
    networks:
      - tracardi-network
    depends_on:
      - redis
      - elasticsearch
      - pulsar
      - mysql

  tracardi-public-api:
    image: tracardi/com-tracardi-api:1.1.10
    container_name: tracardi-public-api
    restart: always
    environment:
      PRODUCTION: "yes"
      EXPOSE_GUI_API: "no"
      <<: *api-config
      <<: *license
    ports:
      - 8585:80
    networks:
      - tracardi-network
    depends_on:
      - redis
      - elasticsearch
      - pulsar
      - mysql

  tracardi-background-worker:
    image: tracardi/background-worker:1.1.10
    container_name: background
    environment:
      PRODUCTION: "yes"
      EXPOSE_GUI_API: "no"
      <<: *api-config
      <<: *license
    networks:
      - tracardi-network
    depends_on:
      - redis
      - elasticsearch
      - pulsar
      - mysql

#  tracardi-tms:
#    image: tracardi/tms:1.1.10
#    container_name: tms
#    restart: always
#    environment:
#      MYSQL_HOST: mysql
#      MYSQL_USERNAME: "root"
#      MYSQL_PASSWORD: "root"
#      LOGGING_LEVEL: "info"
#      LICENSE: ${API_LICENSE}
#      API_KEY: "604e5043-a28f-4b4d-baa7-13eb196e7537"
#      SECRET: "a28f-4b4d-baa7-13eb196e7537604e5043"
#    networks:
#      - tracardi-network
#    depends_on:
#      - mysql
#    ports:
#      - 8383:80


  tracardi-gui:
    image: tracardi/tracardi-com-gui:1.1.10
    container_name: tracardi-gui
    ports:
      - 8787:80
    networks:
      - tracardi-network
    depends_on:
      - tracardi-private-api

#  worker:
#    image: tracardi/update-worker:1.1.10
#    container_name: upgrade-worker
#    environment:
#      ELASTIC_HOST: http://elasticsearch:9200
#      REDIS_HOST: redis://redis
#      PULSAR_HOST: pulsar://pulsar:6650
#      MYSQL_HOST: mysql
#    networks:
#      - tracardi-network

networks:
  tracardi-network:
    external: true