# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tracardi_pro_services.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tracardi_pro_services.proto',
  package='service',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1btracardi_pro_services.proto\x12\x07service\"\r\n\x0b\x45mptyParams\"t\n\x12ServiceDescription\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07traffic\x18\x03 \x01(\t\x12\x0c\n\x04icon\x18\x04 \x01(\t\x12\x0c\n\x04tags\x18\x05 \x03(\t\x12\x0e\n\x06prefix\x18\x06 \x01(\t\"\xa7\x01\n\x16ServiceDescriptionDict\x12?\n\x08services\x18\x01 \x03(\x0b\x32-.service.ServiceDescriptionDict.ServicesEntry\x1aL\n\rServicesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.service.ServiceDescription:\x02\x38\x01\"1\n\x0b\x43redentials\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x16\n\x05Token\x12\r\n\x05token\x18\x01 \x01(\t2\x91\x01\n\x07Service\x12Q\n\x16get_available_services\x12\x14.service.EmptyParams\x1a\x1f.service.ServiceDescriptionDict\"\x00\x12\x33\n\tauthorize\x12\x14.service.Credentials\x1a\x0e.service.Token\"\x00\x62\x06proto3'
)




_EMPTYPARAMS = _descriptor.Descriptor(
  name='EmptyParams',
  full_name='service.EmptyParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=53,
)


_SERVICEDESCRIPTION = _descriptor.Descriptor(
  name='ServiceDescription',
  full_name='service.ServiceDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='service.ServiceDescription.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='service.ServiceDescription.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='traffic', full_name='service.ServiceDescription.traffic', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='icon', full_name='service.ServiceDescription.icon', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tags', full_name='service.ServiceDescription.tags', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prefix', full_name='service.ServiceDescription.prefix', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=171,
)


_SERVICEDESCRIPTIONDICT_SERVICESENTRY = _descriptor.Descriptor(
  name='ServicesEntry',
  full_name='service.ServiceDescriptionDict.ServicesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='service.ServiceDescriptionDict.ServicesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='service.ServiceDescriptionDict.ServicesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=341,
)

_SERVICEDESCRIPTIONDICT = _descriptor.Descriptor(
  name='ServiceDescriptionDict',
  full_name='service.ServiceDescriptionDict',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='services', full_name='service.ServiceDescriptionDict.services', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SERVICEDESCRIPTIONDICT_SERVICESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=341,
)


_CREDENTIALS = _descriptor.Descriptor(
  name='Credentials',
  full_name='service.Credentials',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='service.Credentials.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='service.Credentials.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=392,
)


_TOKEN = _descriptor.Descriptor(
  name='Token',
  full_name='service.Token',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='service.Token.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=416,
)

_SERVICEDESCRIPTIONDICT_SERVICESENTRY.fields_by_name['value'].message_type = _SERVICEDESCRIPTION
_SERVICEDESCRIPTIONDICT_SERVICESENTRY.containing_type = _SERVICEDESCRIPTIONDICT
_SERVICEDESCRIPTIONDICT.fields_by_name['services'].message_type = _SERVICEDESCRIPTIONDICT_SERVICESENTRY
DESCRIPTOR.message_types_by_name['EmptyParams'] = _EMPTYPARAMS
DESCRIPTOR.message_types_by_name['ServiceDescription'] = _SERVICEDESCRIPTION
DESCRIPTOR.message_types_by_name['ServiceDescriptionDict'] = _SERVICEDESCRIPTIONDICT
DESCRIPTOR.message_types_by_name['Credentials'] = _CREDENTIALS
DESCRIPTOR.message_types_by_name['Token'] = _TOKEN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyParams = _reflection.GeneratedProtocolMessageType('EmptyParams', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYPARAMS,
  '__module__' : 'tracardi_pro_services_pb2'
  # @@protoc_insertion_point(class_scope:service.EmptyParams)
  })
_sym_db.RegisterMessage(EmptyParams)

ServiceDescription = _reflection.GeneratedProtocolMessageType('ServiceDescription', (_message.Message,), {
  'DESCRIPTOR' : _SERVICEDESCRIPTION,
  '__module__' : 'tracardi_pro_services_pb2'
  # @@protoc_insertion_point(class_scope:service.ServiceDescription)
  })
_sym_db.RegisterMessage(ServiceDescription)

ServiceDescriptionDict = _reflection.GeneratedProtocolMessageType('ServiceDescriptionDict', (_message.Message,), {

  'ServicesEntry' : _reflection.GeneratedProtocolMessageType('ServicesEntry', (_message.Message,), {
    'DESCRIPTOR' : _SERVICEDESCRIPTIONDICT_SERVICESENTRY,
    '__module__' : 'tracardi_pro_services_pb2'
    # @@protoc_insertion_point(class_scope:service.ServiceDescriptionDict.ServicesEntry)
    })
  ,
  'DESCRIPTOR' : _SERVICEDESCRIPTIONDICT,
  '__module__' : 'tracardi_pro_services_pb2'
  # @@protoc_insertion_point(class_scope:service.ServiceDescriptionDict)
  })
_sym_db.RegisterMessage(ServiceDescriptionDict)
_sym_db.RegisterMessage(ServiceDescriptionDict.ServicesEntry)

Credentials = _reflection.GeneratedProtocolMessageType('Credentials', (_message.Message,), {
  'DESCRIPTOR' : _CREDENTIALS,
  '__module__' : 'tracardi_pro_services_pb2'
  # @@protoc_insertion_point(class_scope:service.Credentials)
  })
_sym_db.RegisterMessage(Credentials)

Token = _reflection.GeneratedProtocolMessageType('Token', (_message.Message,), {
  'DESCRIPTOR' : _TOKEN,
  '__module__' : 'tracardi_pro_services_pb2'
  # @@protoc_insertion_point(class_scope:service.Token)
  })
_sym_db.RegisterMessage(Token)


_SERVICEDESCRIPTIONDICT_SERVICESENTRY._options = None

_SERVICE = _descriptor.ServiceDescriptor(
  name='Service',
  full_name='service.Service',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=419,
  serialized_end=564,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_available_services',
    full_name='service.Service.get_available_services',
    index=0,
    containing_service=None,
    input_type=_EMPTYPARAMS,
    output_type=_SERVICEDESCRIPTIONDICT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='authorize',
    full_name='service.Service.authorize',
    index=1,
    containing_service=None,
    input_type=_CREDENTIALS,
    output_type=_TOKEN,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICE)

DESCRIPTOR.services_by_name['Service'] = _SERVICE

# @@protoc_insertion_point(module_scope)
