event:
  profile:
    traits:
      name: profile@data.pii.firstname
      surname: profile@data.pii.lastname
      email: profile@data.contact.email
  context: off
session:
  matadata: off
profile:
  pii: off